DIR_MODULE_PROCS		:= procs
DIR_INTERFACE_PROCS	:= $(DIR_MODULE_PROCS)
DIR_INTERNAL_PROCS	:= $(DIR_MODULE_PROCS)/_internal

SRC_INTERFACE_PROCS	:= procs.c 
SRC_INTERNAL_PROCS	:= 

OBJ_PROCS			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_PROCS)/, $(SRC_INTERFACE_PROCS:.c=.o))
OBJ_PROCS			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_PROCS)/, $(SRC_INTERNAL_PROCS:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_PROCS)/%.o: $(DIR_SRC)/$(DIR_MODULE_PROCS)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_PROCS)/_internal -c $< -o $@
