DIR_MODULE_PHILOSOPHER		:= philosopher
DIR_INTERFACE_PHILOSOPHER	:= $(DIR_MODULE_PHILOSOPHER)
DIR_INTERNAL_PHILOSOPHER	:= $(DIR_MODULE_PHILOSOPHER)/_internal

SRC_INTERFACE_PHILOSOPHER	:= philosopher.c 
SRC_INTERNAL_PHILOSOPHER	:= _init.c _data.c _day.c _info.c _launch.c 

OBJ_PHILOSOPHER			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_PHILOSOPHER)/, $(SRC_INTERFACE_PHILOSOPHER:.c=.o))
OBJ_PHILOSOPHER			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_PHILOSOPHER)/, $(SRC_INTERNAL_PHILOSOPHER:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_PHILOSOPHER)/%.o: $(DIR_SRC)/$(DIR_MODULE_PHILOSOPHER)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_PHILOSOPHER)/_internal -c $< -o $@
