DIR_MODULE_THREADING		:= threading
DIR_INTERFACE_THREADING	:= $(DIR_MODULE_THREADING)
DIR_INTERNAL_THREADING	:= $(DIR_MODULE_THREADING)/_internal

SRC_INTERFACE_THREADING	:= thread.c 
SRC_INTERNAL_THREADING	:= 

OBJ_THREADING			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_THREADING)/, $(SRC_INTERFACE_THREADING:.c=.o))
OBJ_THREADING			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_THREADING)/, $(SRC_INTERNAL_THREADING:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_THREADING)/%.o: $(DIR_SRC)/$(DIR_MODULE_THREADING)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_THREADING)/_internal -c $< -o $@
