DIR_MODULE_STATES		:= states
DIR_INTERFACE_STATES	:= $(DIR_MODULE_STATES)
DIR_INTERNAL_STATES	:= $(DIR_MODULE_STATES)/_internal

SRC_INTERFACE_STATES	:= states.c 
SRC_INTERNAL_STATES	:= 

OBJ_STATES			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_STATES)/, $(SRC_INTERFACE_STATES:.c=.o))
OBJ_STATES			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_STATES)/, $(SRC_INTERNAL_STATES:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_STATES)/%.o: $(DIR_SRC)/$(DIR_MODULE_STATES)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_STATES)/_internal -c $< -o $@
