DIR_MODULE_PROCESS		:= process
DIR_INTERFACE_PROCESS	:= $(DIR_MODULE_PROCESS)
DIR_INTERNAL_PROCESS	:= $(DIR_MODULE_PROCESS)/_internal

SRC_INTERFACE_PROCESS	:= process.c 
SRC_INTERNAL_PROCESS	:= _check.c 

OBJ_PROCESS			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_PROCESS)/, $(SRC_INTERFACE_PROCESS:.c=.o))
OBJ_PROCESS			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_PROCESS)/, $(SRC_INTERNAL_PROCESS:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_PROCESS)/%.o: $(DIR_SRC)/$(DIR_MODULE_PROCESS)/%.c
	@mkdir -p $(dir $@)
	@printf "\r ⚙️ $(_YELLOW) Compiling$(_RESET) %-60s" "$<"
	@$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_PROCESS)/_internal -c $< -o $@

