DIR_MODULE_SEMAPHORE		:= semaphore
DIR_INTERFACE_SEMAPHORE	:= $(DIR_MODULE_SEMAPHORE)
DIR_INTERNAL_SEMAPHORE	:= $(DIR_MODULE_SEMAPHORE)/_internal

SRC_INTERFACE_SEMAPHORE	:= semaphore.c 
SRC_INTERNAL_SEMAPHORE	:= 

OBJ_SEMAPHORE			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_SEMAPHORE)/, $(SRC_INTERFACE_SEMAPHORE:.c=.o))
OBJ_SEMAPHORE			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_SEMAPHORE)/, $(SRC_INTERNAL_SEMAPHORE:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_SEMAPHORE)/%.o: $(DIR_SRC)/$(DIR_MODULE_SEMAPHORE)/%.c
	@mkdir -p $(dir $@)
	@printf "\r ⚙️ $(_YELLOW) Compiling$(_RESET) %-60s" "$<"
	@$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_SEMAPHORE)/_internal -c $< -o $@

