DIR_MODULE_SORTING		:= sorting
DIR_INTERFACE_SORTING	:= $(DIR_MODULE_SORTING)
DIR_INTERNAL_SORTING	:= $(DIR_MODULE_SORTING)/_internal

SRC_INTERFACE_SORTING	:= sorting.c 
SRC_INTERNAL_SORTING	:= _sorting.c 

OBJ_SORTING			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_SORTING)/, $(SRC_INTERFACE_SORTING:.c=.o))
OBJ_SORTING			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_SORTING)/, $(SRC_INTERNAL_SORTING:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_SORTING)/%.o: $(DIR_SRC)/$(DIR_MODULE_SORTING)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) -I$(DIR_SRC)/$(DIR_MODULE_SORTING)/_internal $(INCLUDE_ALL) -c $< -o $@
