DIR_MODULE_PHILOSOPHERS		:= philosophers
DIR_INTERFACE_PHILOSOPHERS	:= $(DIR_MODULE_PHILOSOPHERS)
DIR_INTERNAL_PHILOSOPHERS	:= $(DIR_MODULE_PHILOSOPHERS)/_internal

SRC_INTERFACE_PHILOSOPHERS	:= life.c watcher.c philosophers.c 
SRC_INTERNAL_PHILOSOPHERS	:= _utils.c _life.c 

OBJ_PHILOSOPHERS			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_PHILOSOPHERS)/, $(SRC_INTERFACE_PHILOSOPHERS:.c=.o))
OBJ_PHILOSOPHERS			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_PHILOSOPHERS)/, $(SRC_INTERNAL_PHILOSOPHERS:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_PHILOSOPHERS)/%.o: $(DIR_SRC)/$(DIR_MODULE_PHILOSOPHERS)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_PHILOSOPHERS)/_internal -c $< -o $@
