DIR_MODULE_UTILS		:= utils
DIR_INTERFACE_UTILS	:= $(DIR_MODULE_UTILS)
DIR_INTERNAL_UTILS	:= $(DIR_MODULE_UTILS)/_internal

SRC_INTERFACE_UTILS	:= utils/utils.c 
SRC_INTERNAL_UTILS	:= #$SRC_INTERNAL

OBJ_UTILS			:= $(addprefix $(DIR_OBJ)/, $(SRC_INTERFACE_UTILS:.c=.o)) # $(DIR_INTERFACE_UTILS)/
OBJ_UTILS			+= $(addprefix $(DIR_OBJ)/, $(SRC_INTERNAL_UTILS:.c=.o)) # $(DIR_INTERNAL_UTILS)/

$(DIR_OBJ)/$(DIR_MODULE_UTILS)/%.o: $(DIR_SRC)/$(DIR_MODULE_UTILS)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_UTILS)/_internal -c $< -o $@
