DIR_MODULE_DEBUG		:= debug
DIR_INTERFACE_DEBUG	:= $(DIR_MODULE_DEBUG)
DIR_INTERNAL_DEBUG	:= $(DIR_MODULE_DEBUG)/_internal

SRC_INTERFACE_DEBUG	:= debug/debug.c 
SRC_INTERNAL_DEBUG	:= #$SRC_INTERNAL

OBJ_DEBUG			:= $(addprefix $(DIR_OBJ)/, $(SRC_INTERFACE_DEBUG:.c=.o)) # $(DIR_INTERFACE_DEBUG)/
OBJ_DEBUG			+= $(addprefix $(DIR_OBJ)/, $(SRC_INTERNAL_DEBUG:.c=.o)) # $(DIR_INTERNAL_DEBUG)/

$(DIR_OBJ)/$(DIR_MODULE_DEBUG)/%.o: $(DIR_SRC)/$(DIR_MODULE_DEBUG)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_DEBUG)/_internal -c $< -o $@
